---
abstract: "Strings with boolean values independent of perl's assumptions"
author:
  - 'everybody <everybody at cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Boolean-String
requires:
  Sub::Exporter: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Boolean-String
version: 0.01
